spring:
  application:
    name: demo

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: trued


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

#환경변수
#DB_URL=jdbc:mariadb://[DB IP주소]:3306/[DB명칭];DB_USERNAME=[사용자 아이디];DB_PASSWORD=[사용자 비밀번호]